
-- Create tables for the Trinks automation

-- Table for storing service data from Trinks
CREATE TABLE IF NOT EXISTS trinks_services (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service_date DATE NOT NULL,
  professional TEXT NOT NULL,
  service_name TEXT NOT NULL,
  category TEXT NOT NULL,
  client_name TEXT,
  value NUMERIC(10,2),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Table for automation logs
CREATE TABLE IF NOT EXISTS automation_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message TEXT NOT NULL,
  is_error BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create indexes for better query performance
CREATE INDEX idx_trinks_services_service_date ON trinks_services (service_date);
CREATE INDEX idx_trinks_services_professional ON trinks_services (professional);
CREATE INDEX idx_trinks_services_category ON trinks_services (category);
CREATE INDEX idx_automation_logs_created_at ON automation_logs (created_at);
