-- Tabela de aniversários (apenas apelido + dia + mês, sem ano para privacidade)
CREATE TABLE IF NOT EXISTS aniversarios (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  apelido TEXT NOT NULL,
  dia SMALLINT NOT NULL CHECK (dia BETWEEN 1 AND 31),
  mes SMALLINT NOT NULL CHECK (mes BETWEEN 1 AND 12),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_aniversarios_mes ON aniversarios (mes);

ALTER TABLE aniversarios ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access to aniversarios"
  ON aniversarios FOR SELECT
  TO public
  USING (true);

-- Seed: 22 profissionais do Studio X
INSERT INTO aniversarios (apelido, dia, mes) VALUES
  ('Talita', 14, 1),
  ('Jane', 25, 1),
  ('Debora', 12, 1),
  ('Elda', 23, 2),
  ('Brenda', 8, 2),
  ('Mity', 15, 3),
  ('Stefanny', 31, 3),
  ('Kelle', 2, 4),
  ('Letícia', 5, 4),
  ('Paula', 25, 7),
  ('Rilley', 10, 7),
  ('Michelle', 13, 8),
  ('Augusto', 23, 8),
  ('Jessica', 29, 8),
  ('Andressa', 24, 8),
  ('Jóia', 6, 9),
  ('Thayna', 13, 9),
  ('Sarah', 29, 9),
  ('Manu', 25, 9),
  ('Ricardo', 20, 10),
  ('Jeniffer', 5, 11),
  ('Cris', 30, 12);
